server:
  port: 8091
  servlet:
    context-path: /
spring:

  mvc:
    favicon:
      enabled: true
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  thymeleaf:
    #缓冲的配置
    cache: false
    encoding: utf-8
    prefix: classpath:/templates
    suffix: .html
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.ly.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.ly.mapper: debug