server:
  port: 8092
  servlet:
    context-path: /
spring:
  thymeleaf:
    #缓冲的配置
    cache: false
    encoding: utf-8
    prefix: classpath:/templates
    suffix: .html

logging:
  level:
    com.ly.mapper: debug

#添加dubbo配制
dubbo:
  scan:
    basePackages: com.ly
  application:
    name: consumer-web
  registry:
    address: zookeeper://192.168.180.160:2181
